apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-side-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multipod-app
  template:
    metadata:
      labels:
        app: multipod-app
    spec:
      containers:
        - name: java-container         
          command: ["sleep", "5100"]
        - name: nginx-container          
          command: ["sleep", "4800"]
