apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipod-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multipod-app
  template:
    metadata:
      labels:
        app: multipod-app
    spec:
      containers:
        - name: java-container
          image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:2.4
          command: ["sleep", "5100"]
        - name: nginx-container
          image: image-registry.openshift-image-registry.svc:5000/openshift/nginx:1.20-ubi7
          command: ["sleep", "4800"]
