apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipod-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multipod-app
  template:
    metadata:
      labels:
        app: multipod-app
    spec:
      containers:
        - name: java-container       
          command: ["sleep", "4900"]
        - name: nginx-container
          command: ["sleep", "4800"]
